### ISSUE TITLE
Controller for root path?

### ISSUE THREAD

**Issue by ghost** [Alex-Levacher/Lumie#18]
Every controller defines his own route over own name, for example:

controllers/project.js
```
[Project]
        public  get     [/project/]
        member  get     [/project/number/:value]
```
project-ctrl.js
```
module.exports = {
    '/': {
        get: {
            action: index,
            level: 'public'
        }
    },

...
```

This creates a path for listen over project/. If do i want to listen over root path?

For example: 
* My `preURL` is `/`.
* I want to listen a request over `/` without another parameter, specific controllers over this clean path.  Is It neccesary do it outside Lumie config?

**Comment by Alex-Levacher** [comment]
Hi @dankkomcg, when #19 will be merged, you will be able to do in your project ctrl:
```js
module.exports = {
    path: '/',
    '/': {
        get: {
            action: index,
            level: 'public'
        }
    }
}
```
