### ISSUE TITLE
preUrl option on lumie load

### ISSUE THREAD

**Issue by kevinmelo** [Alex-Levacher/Lumie#21]
Don't know if it's a bug or not.

If you use single quotes on _preUrl_ **lumie** don't recognize the option only with double quotes

**Comment by Alex-Levacher** [comment]
Hi @kevinmelo, are you still experiencing this issue? As in javascript single quotes and double quotes are both used for writing strings, I have no clue why using preURL with single quotes doesn't work while double quotes do work as mentioned in your issue. I tried to be sure and both work.

**Comment by kevinmelo** [comment]
I tested again, but on linux now and work... i will try again on windows... maybe it's a bug there...
