### ISSUE TITLE
How can I promote Lumie? 

### ISSUE THREAD

**Issue by Alex-Levacher** [Alex-Levacher/Lumie#3]
Hi everyone,
I'm looking for new ideas to promote Lumie. If you have some, don't hesitate to list them below.
I'll share with you the results of the different suggested actions by updating this post with the statistics. 
Thanks ✌🏼

-  Post on Indie Hacker ( [link](https://www.indiehackers.com/forum/show-ih-an-opinionated-npm-module-to-create-better-apps-and-ship-faster-86cf3010ad) ) **11 votes** / **88 visits**
-  Post on EchoJS ( [link](http://www.echojs.com/news/27102) ) **6 votes** / **117 visits**

**Comment by glimow** [comment]
Have you thought about [productHunt](https://www.producthunt.com/)  ? Lumie is definitely a promising idea, I searched a long time for a nicely-structured framework with wide compatibility like this. Will spread the word on my side. Also, I have found no contribution guide but I w'd be happy to make some PR's if you need

**Comment by Alex-Levacher** [comment]
@glimow I’m glad that Lumie matches what you was looking for, and thanks a lot for sharing it 🙏🏼. Yes, posting on PH is definetly something I have to prepare.
You’re right about the contribution guide, I’ll do it.

**Comment by matiit** [comment]
Attend conferences with some good talk? :) 
Good luck!

**Comment by dbengsch** [comment]
Maybe here: https://github.com/rajikaimal/awesome-express
