### ISSUE TITLE
Default value of preURL leads to crashing.

### ISSUE THREAD

**Issue by momocow** [Alex-Levacher/Lumie#7]
https://github.com/Alex-Levacher/Lumie/blob/master/src/index.js#L62

If the `preURL` is not set in options, the error is thrown.

```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
```

**Comment by Alex-Levacher** [comment]
Thanks @momocow for reporting this. Now the fix has been merged and released.
PR ( #8 )
